### ISSUE TITLE
Any example for using this provider?

### ISSUE THREAD

**Issue by chenrui333** [mlafeldt/terraform-provider-launchdarkly#1]
I am curious if you can put a example for how to use this?

**Comment by chenrui333** [comment]
looks like I have to directly clone the repo and make changes on top it, I wonder if there is way that I can integrate as provider into my existing infra codebase.

**Comment by mlafeldt** [comment]
Hey, I somehow missed this issue. Sorry about that.

The README includes an example and some installation instructions: https://github.com/mlafeldt/terraform-provider-launchdarkly#example
